#!/usr/bin/env bash
# Fetch DM Serif Display (Regular + Italic) and JetBrains Mono (variable)
# from Google Fonts' GitHub mirror. Rewrites fonts.css to match the format
# actually produced (woff2 if `woff2_compress` is installed, else ttf).
#
# Run once after clone. Re-runnable — overwrites existing files and CSS.

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
FONTS_DIR="$ROOT/templates/_shared/fonts"
CSS_PATH="$ROOT/templates/_shared/fonts.css"

mkdir -p "$FONTS_DIR"

TTF_BASE="https://raw.githubusercontent.com/google/fonts/main/ofl"

download() {
  local src="$1" dst="$2"
  echo "• $src → $(basename "$dst")"
  curl -fsSL "$TTF_BASE/$src" -o "$dst"
}

# DM Serif Display ships static TTFs (Regular + Italic).
download "dmserifdisplay/DMSerifDisplay-Regular.ttf" "$FONTS_DIR/DMSerifDisplay-Regular.ttf"
download "dmserifdisplay/DMSerifDisplay-Italic.ttf"  "$FONTS_DIR/DMSerifDisplay-Italic.ttf"

# JetBrains Mono ships a variable TTF (wght axis 100–800). Single file.
download "jetbrainsmono/JetBrainsMono%5Bwght%5D.ttf" "$FONTS_DIR/JetBrainsMono-Variable.ttf"

# Optional: compress to woff2 for smaller payload. Both ttf and woff2 work
# with Chrome headless — compression is purely a size win.
EXT="ttf"
FORMAT="truetype"
if command -v woff2_compress >/dev/null 2>&1; then
  for ttf in "$FONTS_DIR"/*.ttf; do
    woff2_compress "$ttf" >/dev/null
    rm -f "$ttf"
  done
  EXT="woff2"
  FORMAT="woff2"
  echo "✓ converted to woff2"
else
  echo "ℹ woff2_compress not found (brew install woff2 for smaller files); keeping .ttf"
fi

# Regenerate fonts.css to reference files in the format we have.
cat > "$CSS_PATH" <<EOF
/* Generated by scripts/download-fonts.sh. Re-run the script to regenerate. */

@font-face {
  font-family: 'DM Serif Display';
  font-style: normal;
  font-weight: 400;
  font-display: block;
  src: url('fonts/DMSerifDisplay-Regular.$EXT') format('$FORMAT');
}
@font-face {
  font-family: 'DM Serif Display';
  font-style: italic;
  font-weight: 400;
  font-display: block;
  src: url('fonts/DMSerifDisplay-Italic.$EXT') format('$FORMAT');
}
@font-face {
  font-family: 'JetBrains Mono';
  font-style: normal;
  /* Variable wght axis 100–800. */
  font-weight: 100 800;
  font-display: block;
  src: url('fonts/JetBrainsMono-Variable.$EXT') format('$FORMAT');
}
EOF

echo "✓ fonts in $FONTS_DIR"
ls -1 "$FONTS_DIR"
echo ""
echo "✓ fonts.css regenerated → $CSS_PATH ($EXT / $FORMAT)"
